### ISSUE TITLE
Error bij nieuw uur

### ISSUE THREAD

**Issue by finnie2006** [VLGNL/IcecastRecorder#4]
Als het nieuwe uur begint dan stopt hij, heb hem gestart door midddel van node Launcher.js
```
/var/www/tmp/src/Cron.js:60
        kill(RunExternS.pid);
        ^

ReferenceError: kill is not defined
    at CronJob.<anonymous> (/var/www/tmp/src/Cron.js:60:9)
    at CronJob.fireOnTick (/var/www/tmp/node_modules/cron/lib/cron.js:600:23)
    at Timeout.callbackWrapper [as _onTimeout] (/var/www/tmp/node_modules/cron/lib/cron.js:667:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
Icecast Recorder exited with code 1
```

**Comment by CrazyVinc** [comment]
Ik heb zojuist een update gevonden op me PC, De fout komt bij mij niet terug als ik deze update gebruik.
Als je hierna nog last hebt van de error hoor ik het graag!
